spring.application.name=isaBack

# DATABASE - POSTGRESQL
spring.datasource.url=jdbc:postgresql://localhost:5432/isa
spring.datasource.username=postgres
spring.datasource.password=projekat
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=tzKFtjKF0ZqYWfO1lvDVIXCVyvVZGERS
jwt.expiration=86400000

# SERVER
server.port=8080

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=olgaponjevic@gmail.com
spring.mail.password=qpeposfibquiacqh
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.activation.url=http://localhost:4200/activate
app.activation.token-expiration-hours=24

app.upload.dir=uploads
spring.servlet.multipart.max-file-size=200MB
spring.servlet.multipart.max-request-size=210MB

app.upload.simulate-slow=false
app.upload.timeout-seconds=30